# Generated by Django 5.0.1 on 2024-01-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
