name: CD Pipeline

on:
  workflow_run:
    workflows: ["push to docker hub"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps: 
      - name: Pull Docker image
        run: sudo docker pull ashutosh211/noteit:latest

      - name: Delete Old docker container
        run: sudo docker rm -f noteitbackend || true

      - name: Run Docker Container
        run: |
          echo "DEBUG=${{ secrets.DEBUG }}" > env.list
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> env.list
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> env.list
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> env.list
          echo "DB_USER=${{ secrets.DB_USER }}" >> env.list
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> env.list
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> env.list
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> env.list

          sudo docker run -d -p 8080:8080 --name noteitbackend --env-file env.list ashutosh211/noteit:latest
