name: CD Pipeline

on:
  workflow_run:
    workflows: ["push to docker hub"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps: 
      - name: Pull Docker image
        run: sudo docker pull ashutosh211/noteit:latest

      - name: Delete Old docker container
        run: sudo docker rm -f noteitbackend || true

      - name: check
        run: sudo ls
      

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name noteitbackend -e DEBUG=${{ secrets.DEBUG }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -e ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} ashutosh211/noteit:lates

